#!/bin/bash
set -e

# Elite Alpha Mirror Bot - Master Setup Script
# Auto-generated by repository optimizer

echo '🚀 Elite Alpha Mirror Bot Setup'
echo '================================'

# Create virtual environment
if [ ! -d venv ]; then
    python3 -m venv venv
    echo '✅ Virtual environment created'
fi

# Activate virtual environment
source venv/bin/activate

# Install dependencies
pip install --upgrade pip
pip install -r requirements.txt
echo '✅ Dependencies installed'

# Setup configuration
if [ ! -f .env ]; then
    cp .env.example .env 2>/dev/null || echo '⚠️  Please create .env file manually'
fi

echo '✅ Setup complete! Run ./start.sh to begin'
