version: 1
disable_existing_loggers: false

formatters:
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(filename)s:%(lineno)d - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  simple:
    format: '%(asctime)s - %(levelname)s - %(message)s'
    datefmt: '%H:%M:%S'

  json:
    format: '{"timestamp": "%(asctime)s", "level": "%(levelname)s", "logger": "%(name)s", "message": "%(message)s", "file": "%(filename)s", "line": %(lineno)d}'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: logs/bot.log
    maxBytes: 104857600  # 100MB
    backupCount: 5

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/errors.log
    maxBytes: 52428800  # 50MB
    backupCount: 3

  trade_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: logs/trades.log
    maxBytes: 52428800  # 50MB
    backupCount: 10

loggers:
  trading:
    level: INFO
    handlers: [trade_file]
    propagate: false

  monitoring:
    level: INFO
    handlers: [file]
    propagate: true

  rust:
    level: INFO
    handlers: [file]
    propagate: true

root:
  level: INFO
  handlers: [console, file, error_file]
