# Security Configuration for Production
security:
  # API Rate Limiting
  rate_limits:
    etherscan: 5  # requests per second
    okx: 10       # requests per second
    dexscreener: 2 # requests per second
    
  # Input Validation
  validation:
    wallet_address_regex: "^0x[a-fA-F0-9]{40}$"
    token_address_regex: "^0x[a-fA-F0-9]{40}$"
    max_amount: 1000000  # Max USD amount
    min_amount: 1        # Min USD amount
    
  # API Security
  api_security:
    require_https: true
    verify_ssl: true
    timeout_seconds: 30
    max_redirects: 3
    
  # Audit Logging
  audit:
    log_all_trades: true
    log_api_calls: true
    log_errors: true
    retention_days: 365
    
  # Emergency Controls
  emergency:
    max_consecutive_losses: 3
    circuit_breaker_threshold: 0.10  # 10% loss
    emergency_stop_file: "/tmp/emergency_stop"
